development:
  adapter: postgresql
  encoding: utf8
  database: klipbox_development
  username: postgres
  password: 93176425
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: klipbox_teste
  username: postgres
  password: 93176425
  host: localhost